version: "3.9"

services:
  rabbitmq:
    container_name: Kumiko-IPC-RabbitMQ
    image: rabbitmq:3-management
    env_file:
      - .env
    ports:
      - 5672:5672
      - 15672:15672
    hostname: kumiko_ipc

  kumiko_ipc:
    container_name: Kumiko-IPC
    image: no767/kumiko-ipc:edge
    env_file:
      - .env
    restart: always