version: "3.9"

services:
  rabbitmq:
    container_name: Kumiko-IPC-RabbitMQ
    image: rabbitmq:3-management
    env_file:
      - .env
    ports:
      - 5672:5672
      - 15672:15672
    hostname: kumiko_ipc

  redis:
    container_name: Kumiko-IPC-Redis
    image: redis:7
    ports: 
      - 6379:6379
    volumes:
      - redis_volume:/data
    command: redis-server --save 60 1 --loglevel warning

volumes:
  redis_volume:
